# This is a basic workflow to help you get started with Actions

name: .NET 5

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' 

    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef

    - name: Install dependencies
      run: dotnet restore CompanyName.GatewayManagement.sln

    - name: Build
      run: dotnet build CompanyName.GatewayManagement.sln --configuration Release --no-restore
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: run GatewayManagement.Domain.Tests
        run: dotnet test --no-restore tests\CompanyName.GatewayManagement.Domain.Tests\CompanyName.GatewayManagement.Domain.Tests.csproj
        
